# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 893f0db45f1b8fa08a871f5ff02cf1b5d05a8f4f767f7ee877efa1f53feb121d3674bdbe0ff94742328264bfcc15c1a7e119c17ebfca17c2212de627e1b01232

test:
  secret_key_base: d05f2e1180c2638e7726b9108d98fc8832c5af2143b6591c6a743b043450233ea4ef55a1dd4f042745fa9c7abb98324dc8e4c074286ad3442a1555a2cb41aac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
